/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/trust-score/{address}": {
    /**
     * Retrieve trust score for a Stellar address
     * @description Returns the current Credence trust score and tier for the given Stellar public key. The score is recomputed on-chain whenever a new attestation is submitted or a bond matures.
     */
    get: operations["getTrustScore"];
  };
  "/transactions": {
    /**
     * List recent protocol transactions
     * @description Returns a cursor-paginated list of transaction events across all protocol actions (bond creation, withdrawal, attestation) visible to the authenticated wallet. Results are ordered newest-first.
     */
    get: operations["listTransactions"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description Lifecycle state of a USDC bond.
     * @enum {string}
     */
    BondStatus: "active" | "pending" | "settled" | "slashed" | "cancelled";
    /**
     * @description Credence trust tier derived from the on-chain score.
     * @enum {string}
     */
    TrustTier: "bronze" | "silver" | "gold" | "platinum";
    /**
     * @description Protocol action that produced a transaction record.
     * @enum {string}
     */
    TransactionType: "bond" | "withdraw" | "attestation";
    /**
     * @description Settlement state of the on-chain operation.
     * @enum {string}
     */
    TransactionStatus: "pending" | "confirmed" | "failed";
    /** @description Trust-score snapshot for a single Stellar address. */
    TrustScore: {
      /**
       * @description Stellar public key (G...) of the scored account.
       * @example GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
       */
      address: string;
      /**
       * @description Numeric trust score (higher is better).
       * @example 840
       */
      score: number;
      tier: components["schemas"]["TrustTier"];
      /**
       * @description Count of verified attestations backing this score.
       * @example 12
       */
      attestations: number;
      /**
       * Format: date-time
       * @description ISO 8601 timestamp of the last score update.
       * @example 2026-06-29T10:00:00Z
       */
      updatedAt: string;
    };
    /** @description A USDC bond registered in the Credence protocol. */
    Bond: {
      /** @description Stable unique identifier for this bond record. */
      id: string;
      /** @description Stellar public key of the bond creator. */
      borrower: string;
      /** @description Stellar public key of the counter-party, if assigned. */
      lender?: string;
      /**
       * @description Bond amount as a decimal string (avoids float precision issues), denominated in the asset field.
       *
       * @example 1000.00
       */
      amount: string;
      /**
       * @description Asset code locked in the bond (e.g. USDC).
       * @example USDC
       */
      asset: string;
      status: components["schemas"]["BondStatus"];
      /**
       * Format: date-time
       * @description ISO 8601 timestamp when the bond was created.
       */
      createdAt: string;
      /**
       * Format: date-time
       * @description ISO 8601 timestamp when the bond lock expires, if set.
       */
      maturesAt?: string;
    };
    /** @description A single protocol transaction event visible in the history feed. */
    Transaction: {
      /** @description Unique stable identifier for this record. */
      id: string;
      type: components["schemas"]["TransactionType"];
      /**
       * @description USDC amount involved in the transaction, if applicable.
       * @example 500
       */
      amountUsdc?: number;
      /**
       * Format: date-time
       * @description ISO 8601 timestamp of the event.
       */
      timestamp: string;
      status: components["schemas"]["TransactionStatus"];
      /**
       * @description On-chain transaction hash for the Stellar explorer.
       * @example b6d396a84d41bf162d05f32a51f8a846b0a6fb2abccedb441f71f11e9f1a2380
       */
      hash: string;
    };
    /** @description Cursor-paginated list of Transaction records. */
    TransactionList: {
      items: components["schemas"]["Transaction"][];
      /** @description Opaque pagination cursor. Include as the `cursor` query parameter in the next request to retrieve the following page. Absent when there are no more results. */
      nextCursor?: string;
    };
    /** @description Simple message envelope returned for errors and confirmations. */
    ApiMessageResponse: {
      /**
       * @description Human-readable message describing the outcome.
       * @example Address not found.
       */
      message: string;
    };
    /** @description The authenticated tenant context. */
    Tenant: {
      /**
       * @description Stable public identifier for the active tenant (Stellar public key).
       * @example GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
       */
      tenantId: string;
    };
  };
  responses: {
    /** @description The request was malformed or contained invalid parameters. */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["ApiMessageResponse"];
      };
    };
    /** @description The requested resource does not exist. */
    NotFound: {
      content: {
        "application/json": components["schemas"]["ApiMessageResponse"];
      };
    };
  };
  parameters: {
    /**
     * @description Stellar public key (56-character base32 G... string).
     * @example GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
     */
    StellarAddress: string;
    /** @description Pagination cursor returned by a previous list response. */
    CursorParam?: string;
    /** @description Maximum number of items per page (1–100, default 20). */
    LimitParam?: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Retrieve trust score for a Stellar address
   * @description Returns the current Credence trust score and tier for the given Stellar public key. The score is recomputed on-chain whenever a new attestation is submitted or a bond matures.
   */
  getTrustScore: {
    parameters: {
      path: {
        address: components["parameters"]["StellarAddress"];
      };
    };
    responses: {
      /** @description Trust score returned successfully. */
      200: {
        content: {
          "application/json": components["schemas"]["TrustScore"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * List recent protocol transactions
   * @description Returns a cursor-paginated list of transaction events across all protocol actions (bond creation, withdrawal, attestation) visible to the authenticated wallet. Results are ordered newest-first.
   */
  listTransactions: {
    parameters: {
      query?: {
        cursor?: components["parameters"]["CursorParam"];
        limit?: components["parameters"]["LimitParam"];
      };
    };
    responses: {
      /** @description Paginated transaction list returned successfully. */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionList"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
}
